name: build

on:
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
        
      - name: Build
        run: |
          cd build
          make

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
        
      - name: Build
        run: |
          cd build
          make

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
        
      - name: Build
        run: |
          cd build
          cmake --build . --config Release
